"""Train router v1: predict P(cheap model answers correctly | prompt).

Same architecture as v0 (frozen MiniLM embeddings + class-weighted logistic
regression) — deliberately unchanged, so any improvement over v0 is
attributable to the label source: verifiable correctness instead of noisy
human preference votes.

Data: labels_probe_prompts.parquet + labels_main_prompts.parquet (both
generated by scripts/generate_labels.py against Haiku 4.5 / Opus 4.8).
Split: 70/15/15 stratified by (source, cheap_correct) so every difficulty
tier appears in every split.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split

from router.embed import embed_split

ROOT = Path(__file__).resolve().parent.parent
DATA, ART = ROOT / "data", ROOT / "artifacts" / "v1"


def main() -> None:
    ART.mkdir(parents=True, exist_ok=True)
    parts = [
        pd.read_parquet(DATA / f)
        for f in ("labels_probe_prompts.parquet", "labels_main_prompts.parquet")
        if (DATA / f).exists()
    ]
    df = pd.concat(parts, ignore_index=True)
    # The router embeds the bare question, not our answer-format suffix.
    df["prompt_text"] = df["prompt"].str.split("\n\nSolve step by step").str[0].str.split(
        "\n\nThink briefly").str[0]
    print(f"total labeled prompts: {len(df)}")
    print(f"P(cheap correct) overall: {df['cheap_correct'].mean():.3f}")

    # Stratify by tier only — the (tier, correct) cells are too small (e.g. a
    # single gsm8k prompt Haiku got wrong) for two-level stratification.
    train, rest = train_test_split(df, test_size=0.3, random_state=0, stratify=df["source"])
    val, test = train_test_split(rest, test_size=0.5, random_state=0, stratify=rest["source"])
    for name, part in (("train", train), ("val", val), ("test", test)):
        part.to_parquet(DATA / f"v1_split_{name}.parquet", index=False)
        print(f"{name}: {len(part)} rows, P(cheap correct)={part['cheap_correct'].mean():.3f}")

    X_train = embed_split(train, DATA, "v1_train")
    X_val = embed_split(val, DATA, "v1_val")

    clf = LogisticRegression(max_iter=2000, C=1.0, class_weight="balanced")
    clf.fit(X_train, train["cheap_correct"])

    p_val = clf.predict_proba(X_val)[:, 1]
    print(f"val AUC (predicting cheap-correct): {roc_auc_score(val['cheap_correct'], p_val):.4f}")
    print(f"val acc@0.5: {accuracy_score(val['cheap_correct'], p_val > 0.5):.4f}")

    joblib.dump(clf, ART / "model.joblib")
    print(f"saved {ART}/model.joblib")


if __name__ == "__main__":
    main()
